name: Advenced Build WSA
on:
  workflow_dispatch:
    inputs:
      arch:
        type: choice
        description: "Architecture:"
        required: true
        options: [x64, arm64]
        default: x64
      custom-wsa:
        description: "Original WSA URL"
        required: false
        type: string
      gapps-brand:
        type: choice
        description: "GApps brand. “none“ for no integration of GApps:"
        required: true
        options: [MindTheGapps, none]
        default: MindTheGapps
      root-sol:
        type: choice
        description: "Root solution. “none“ - without root:"
        required: true
        options: [magisk, none]
        default: magisk
      magisk-ver:
        type: choice
        description: "Magisk version:"
        required: true
        options: [stable, beta, canary, debug]
        default: stable
      remove-amazon:
        type: choice
        description: "Remove or keep Amazon Appstore:"
        required: true
        options: [--remove-amazon, Keep Amazon]
        default: --remove-amazon
jobs:
  Build-WSA:
    name: Build WSA
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update;sudo apt-get install -y setools lzip wine patchelf e2fsprogs python3-pip aria2 p7zip-full attr xz-utils unzip cabextract
          sudo wget -P /usr/local/bin/ https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
          sudo chmod +x /usr/local/bin/winetricks
          python3 -m pip install requests
          winetricks msxml6
      - uses: actions/checkout@v3
        with:
          repository: LSPosed/MagiskOnWSALocal
          path: MagiskOnWSALocal
      - name: Download Original WSA
        run: |
          aria2c -d ./MagiskOnWSALocal/download/ -o wsa-retail.zip ${{ inputs.custom-wsa }}
          aria2c -d ./download/ https://download.microsoft.com/download/4/7/c/47c6134b-d61f-4024-83bd-b9c9ea951c25/appx/Microsoft.VCLibs.x64.14.00.Desktop.appx
          aria2c -d ./download/xaml https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.8.2.nupkg
          7z x ./download/xaml/*.nupkg -o./download/xaml/
          mv ./download/xaml/tools/AppX/x64/Release/*.appx ./download/Microsoft.UI.Xaml_x64.appx
          rm -rf ./download/xaml
      - name: Build WSA
        run: |
          cd ./MagiskOnWSALocal
          scripts/build.sh \
          --arch ${{ inputs.arch }} \
          --release-type retail \
          --skip-download-wsa \
          ${{ inputs.remove-amazon }} \
          --magisk-ver ${{ inputs.magisk-ver }} \
          --gapps-brand ${{ inputs.gapps-brand }} \
          --root-sol ${{ inputs.root-sol }}
      - name: Archiving and compressing artifact
        run: |
          cd MagiskOnWSALocal/output
          7z a -tzip -mx=4 -saa *
      - name: Upload a Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: MagiskOnWSALocal/output/*
          tag_name: WSA
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
